# Generated by Django 4.0.6 on 2022-07-14 01:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('songs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='The name of the playlist', max_length=100)),
                ('is_private', models.BooleanField(default=True, help_text='Whether to let other users to watch/edit the playlist')),
                ('songs', models.ManyToManyField(help_text='the assosiated songs', to='songs.song')),
            ],
        ),
    ]
